version: '3'

services:
  saltcorn:
    image: saltcorn/saltcorn:latest
    command: serve
    container_name: saltcorn
    ports:
      - "3000:3000"
    environment:
      - SQLITE_FILEPATH=/db/db.sqlite
      - SALTCORN_SESSION_SECRET=s3cr3t
      #- DATABASE_URL=postgresql://127.0.0.1:5432/saltcorn
      #- PGUSER=aleixmt
      #- PGHOST=localhost
      #- PGPORT=5432
      #- PGPASSWORD=chemistry
      #- PGDATABASE=saltcorn
    volumes:
      - ./saltcorn_db:/db